# Generated by Django 5.2.9 on 2025-12-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Mark this post as featured to display it in the featured section",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
