# Generated by Django 5.2.9 on 2025-12-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
